[project]
name = "ot-benchmark-pyre"
version = "0.1.0"
description = "Benchmarking pyre's ability to type-check occurrence typing"
requires-python = ">=3.13.0"

[tool.pyre]
include = ["*.py"]
venvPath = "."
venv = ".venv"
reportUnusedImport = false
